# Generated by Django 2.2.6 on 2019-11-28 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(blank=True, max_length=100, null=True)),
                ('petition', models.CharField(blank=True, max_length=100, null=True)),
                ('detection', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
