# Generated by Django 2.2.6 on 2019-11-29 13:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('aplication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Variables',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('var_type', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
