# Generated by Django 2.2.6 on 2019-11-29 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplication', '0002_variables'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeVariable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='variables',
            name='var_type',
        ),
        migrations.AddField(
            model_name='variables',
            name='var_type',
            field=models.ManyToManyField(to='aplication.TypeVariable'),
        ),
    ]
