# Generated by Django 2.2.6 on 2019-11-29 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplication', '0003_auto_20191129_1718'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variables',
            name='var_type',
        ),
        migrations.DeleteModel(
            name='TypeVariable',
        ),
        migrations.DeleteModel(
            name='Variables',
        ),
    ]
